feat(books): implemented User entity and Role entity
YevheniiKilovyi/book-store-app pull request #10
Opened 2023-08-18 10:35 UTC by YevheniiKilovyi

2023-08-23 17:37 UTC, okuzan requested changes

2023-08-23 17:37 UTC, okuzan commented on src/main/java/com/example/bookstoreapp/model/User.java
> +                .map(r -> new SimpleGrantedAuthority(r.getRoleName().name()))
```suggestion
                .map(role -> new SimpleGrantedAuthority(role.getRoleName().name()))

```

2023-08-23 17:37 UTC, okuzan commented on src/main/java/com/example/bookstoreapp/security/jwt/JwtAuthenticationFilter.java
> +        System.out.println("getting token by header");
remove

2023-08-23 17:37 UTC, okuzan commented on src/main/java/com/example/bookstoreapp/security/jwt/JwtAuthenticationFilter.java
> +        }
```suggestion
        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(TOKEN_PREFIX)) {
            return bearerToken.substring(TOKEN_PREFIX.length());
        }

```

2023-08-23 17:37 UTC, okuzan commented on src/main/java/com/example/bookstoreapp/security/jwt/JwtUtil.java
> +        System.out.println("token validation");
use logger instead

2023-08-23 17:37 UTC, okuzan commented on src/main/java/com/example/bookstoreapp/security/CustomUserDetailsService.java
> +                new RegistrationException("Can't find user by username" + username));
```suggestion
                new EntityNotFoundException("Can't find user by username" + username));
```

2023-08-25 10:47 UTC, aaananas approved these changes

2023-08-26 08:33 UTC, merged